/* ═══════════════════════════════════════════════════
   CREATIVES ARCHIVE — data
   The lists are generated by scripts/prepare-archive.ts (archive.generated.json);
   names and wording come from src/content/archive.ts.
   ═══════════════════════════════════════════════════ */

import generated from './archive.generated.json';
import { archiveContent } from '../content/archive';

export type ArchiveImageType = 'post' | 'story' | 'reel-cover' | 'banner';

export type ArchiveImage = {
  /** Default WebP candidate (about 1000px wide) */
  src: string;
  /** WebP candidates; the same files exist as .avif */
  srcset: string;
  w: number;
  h: number;
  /** Tiny blurred placeholder (data URI) */
  lqip: string;
  type: ArchiveImageType;
  /** Original file name, for traceability */
  file: string;
};

export type ArchiveItem = { kind: 'single'; image: ArchiveImage } | { kind: 'carousel'; images: ArchiveImage[] };

export type ArchiveBrand = {
  slug: string;
  name: string;
  /** Sampled from the creatives (or set in the content file) */
  color: string;
  about: string;
  aboutTodo?: boolean;
  /** Number of creatives (every carousel slide counts) */
  count: number;
  items: ArchiveItem[];
};

export type ArchiveFlyer = ArchiveImage & { title: string };

export type ArchiveEmailer = { slug: string; from: string; subject: string; image: ArchiveImage };

export type BrochurePage = { src: string; hi: string; w: number; h: number; lqip: string };

export type Brochure = {
  slug: string;
  name: string;
  /** book = page-flip reader · gatefold = hinged panels · scroll = long sheets read top to bottom */
  kind: 'book' | 'gatefold' | 'scroll';
  pageCount: number;
  /** width / height of one page */
  pageAspect: number;
  spineColor: string;
  /** Shelf cover when it is not simply the first page */
  cover?: string;
  pages: BrochurePage[];
  /** Brij Garden: a cover, the two closed gates, four inside panels and the back, as delivered */
  gatefold?: { cover: BrochurePage; gates: BrochurePage[]; inside: BrochurePage[]; back: BrochurePage; panelWidths: number[] };
};

type Generated = {
  brands: { slug: string; color: string; count: number; items: ArchiveItem[] }[];
  flyers: ArchiveImage[];
  emailers: { slug: string; image: ArchiveImage }[];
  brochures: Omit<Brochure, 'name'>[];
};

const raw = generated as unknown as Generated;

const titleCase = (slug: string) => slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

const brands: ArchiveBrand[] = raw.brands.map((b) => {
  const copy = archiveContent.brands[b.slug];
  return {
    ...b,
    name: copy?.name ?? titleCase(b.slug),
    color: copy?.color ?? b.color,
    about: copy?.about ?? '',
    aboutTodo: copy?.aboutTodo,
  };
});

const flyers: ArchiveFlyer[] = raw.flyers.map((f) => ({
  ...f,
  title: archiveContent.flyers.titles.find((t) => f.file.toLowerCase().includes(t.match))?.title ?? titleCase(f.file.replace(/\.[a-z]+$/i, '')),
}));

const emailers: ArchiveEmailer[] = raw.emailers.map((e) => ({
  ...e,
  from: archiveContent.emailers.items[e.slug]?.from ?? 'Newsletter',
  subject: archiveContent.emailers.items[e.slug]?.subject ?? titleCase(e.slug),
}));

const brochures: Brochure[] = raw.brochures.map((b) => ({ ...b, name: archiveContent.brochures.names[b.slug] ?? titleCase(b.slug) }));

export const archive = {
  /** Menu order: Honeymoon Inn, Jakpower, SRJ, Jovira, Terso, Unipin */
  brands,
  flyers,
  emailers,
  brochures,
  totalCreatives: brands.reduce((n, b) => n + b.count, 0),
};

/** Every image of an item, cover first */
export const imagesOf = (item: ArchiveItem): ArchiveImage[] => (item.kind === 'single' ? [item.image] : item.images);

/** The same srcset in AVIF (the pipeline writes both formats side by side) */
export const avifSet = (srcset: string) => srcset.replace(/\.webp/g, '.avif');

/** Smallest candidate of a srcset, for thumbnails */
export const smallest = (img: ArchiveImage) => img.srcset.split(',')[0].trim().split(' ')[0];
