/* ═══════════════════════════════════════════════════
   PACKAGING CHAPTER — data + wording
   Sizes, placeholders and video facts are generated by scripts/prepare-packaging.ts
   (packaging.generated.json). Everything a visitor reads is hand-editable here.
   ═══════════════════════════════════════════════════ */

import generated from './packaging.generated.json';

export type PackImage = {
  src: string;
  /** WebP candidates; the same files exist as .avif (only where the pipeline wrote several widths) */
  srcset?: string;
  w: number;
  h: number;
  /** Tiny blurred placeholder (data URI) */
  lqip: string;
};

export type PackStep = { label: string; text: string };

export type PackMedia = {
  key: string;
  /** Shown under the thumbnail and in the viewer's caption */
  label: string;
  image: PackImage;
  /** Flat artwork: shown on a white sheet and zoomable (click or pinch, drag to pan) */
  flat?: boolean;
  /** Transparent cut-out (the jar poster): no frame, no shadow box */
  cutout?: boolean;
  /** CSS object-position used wherever this image is cropped */
  objectPosition?: string;
};

export type PackProject = {
  slug: string;
  name: string;
  /** Space Mono line: product ✦ brand ✦ year */
  meta: string;
  /** One line for the cluster header, max 16 words */
  line: string;
  steps: PackStep[];
  swatches: string[];
  gallery: PackMedia[];
};

type Generated = {
  video: {
    available: boolean;
    w?: number;
    h?: number;
    'croppd-1'?: { src: string; duration: number; first: string; last: string };
    'croppd-2'?: { src: string; duration: number; first: string; last: string };
  };
  images: Record<string, PackImage>;
  swatches: Record<string, string[]>;
};

const gen = generated as unknown as Generated;
const img = (key: string): PackImage => gen.images[key] ?? { src: '', w: 1, h: 1, lqip: '' };
/** A frame of the video as an image (posters are 1280 × 720 with alpha) */
const frame = (src: string): PackImage => ({ src, w: gen.video.w ?? 1280, h: gen.video.h ?? 720, lqip: '' });

/** The same srcset in AVIF */
export const avifSet = (srcset: string) => srcset.replace(/\.webp/g, '.avif');

/* ── Featured: Croppd Honey ── */

const v1 = gen.video['croppd-1'];
const v2 = gen.video['croppd-2'];

export const honeyVideo = {
  available: gen.video.available && !!v1 && !!v2,
  /** width / height of the video box */
  aspect: (gen.video.w ?? 1280) / (gen.video.h ?? 720),
  /** Step 1: the flat label wraps onto the jar. `src` has no extension (.webm / -stacked.mp4) */
  wrap: { src: v1?.src ?? '', duration: v1?.duration ?? 4, first: v1?.first ?? '', last: v1?.last ?? '' },
  /** Step 2: the jar turns and lands on its wooden board */
  land: { src: v2?.src ?? '', duration: v2?.duration ?? 4, first: v2?.first ?? '', last: v2?.last ?? '' },
  /** Seconds each beat takes on screen: the 4s videos are played faster to land in this time */
  beat: 1.5,
  /** How much the camera pushes in while the label becomes a jar (the jar is half the frame wide) */
  zoom: 1.6,
  /** Where the pinned scene fires its two steps, as a share of the pin */
  thresholds: [0.3, 0.65] as [number, number],
  /** Length of the pin, in % of the viewport height */
  pin: 220,
};

export const honey: PackProject = {
  slug: 'croppd-honey',
  name: 'Croppd Honey',
  meta: 'RAW HONEY JAR, 250 G ✦ CROPPD ✦ 2025',
  line: 'Raw, unprocessed honey in a jar that feels poured, not manufactured.',
  steps: [
    { label: 'BRIEF', text: 'Raw, unprocessed honey with zero preservatives, for a shelf full of jars that all claim to be pure.' },
    { label: 'CONCEPT', text: 'A hand-drawn wordmark, watercolour blossoms and dripping comb on warm cream paper, so the jar feels poured rather than manufactured.' },
    { label: 'LABEL', text: 'One wrap-around label planned flat first: the story on the left, the wordmark up front, nutrition and legal on the right, so nothing lands on the seam.' },
    { label: 'ON SHELF', text: 'On the table it reads the way it should: honest, warm and straight from the hive.' },
  ],
  swatches: ['#F6EFD9', '#E9A21B', '#5A2E1B'],
  gallery: [
    { key: 'jar', label: 'Jar', image: frame(v2?.last ?? ''), cutout: true },
    { key: 'label', label: 'Label, flat', image: img('croppd-honey/label'), flat: true },
    { key: 'studio', label: 'Studio shot', image: img('croppd-honey/studio'), objectPosition: '50% 55%' },
    { key: 'shelf', label: 'Store shelf', image: img('croppd-honey/shelf'), objectPosition: '50% 50%' },
    { key: 'hero', label: 'Campaign hero', image: img('croppd-honey/hero') },
  ],
};

/** "From studio to shelf": the row right after the featured scene */
export const studioShelf = {
  kicker: 'CROPPD HONEY ✦ IN THE WILD',
  title: 'FROM STUDIO TO SHELF',
  /** Max 30 words */
  intro: 'Same label, two rooms. Alone under studio light, then stacked six high in a shop. It has to read the same in both.',
  /** Captions describe only what each photo shows. Max 40 words each */
  shots: [
    {
      key: 'studio',
      tag: '01 ✦ STUDIO',
      label: 'STUDIO',
      text: 'One jar on a round wooden board, a dipper on one side and a piece of comb on the other. In clean, warm light the cream label, the hand-drawn Honey and the small watercolour comb carry the whole jar.',
    },
    {
      key: 'shelf',
      tag: '02 ✦ SHELF',
      label: 'SHELF',
      text: 'Six jars stacked in a pyramid on a wooden counter, shop shelves blurred behind them. From a few steps back the wordmark is still the first thing you read, and the cream label holds against all that wood.',
    },
  ],
  /** Read off the label artwork itself (croppd honey label.png) */
  facts: [
    { label: 'NET WEIGHT', value: '250 g, glass jar' },
    { label: 'ON THE FRONT', value: 'Hand-drawn “Honey” wordmark ✦ “From Hive to Jar”' },
    { label: 'CLAIMS', value: '100% pure and natural ✦ No added sugar ✦ No preservatives ✦ Rich in natural enzymes and antioxidants' },
    { label: 'ON THE BACK', value: 'Nutrition per 100 g and per 20 g serving ✦ Ingredients: 100% pure natural honey ✦ FSSAI licence ✦ Veg mark ✦ Barcode' },
  ],
};

/* ── More packaging ── */

export const moreHeader = { kicker: 'MORE PACKAGING', title: 'ON OTHER SHELVES' };

/** The first gallery item is the main tile; `hover` is the flat artwork it dissolves to */
export const moreProjects: Array<PackProject & { hover?: string }> = [
  {
    slug: 'profoods-makhana',
    name: 'ProFoods Makhana',
    meta: 'MAKHANA SNACK POUCH ✦ PROFOODS ✦ 2025',
    line: 'Superfood makhana for people who count calories but refuse to snack boring.',
    steps: [
      { label: 'BRIEF', text: 'A superfood makhana brand for calorie-conscious, nutrition-focused people.' },
      { label: 'CONCEPT', text: 'A confident yellow pouch with an illustrated farmer and his basket of makhana, so it reads healthy from across the aisle without looking like medicine.' },
      { label: 'ON SHELF', text: 'In the hand and on the table, the pouch holds its own in a real snacking moment.' },
    ],
    swatches: ['#F5C518', '#2D2D2D', '#FFFFFF'],
    hover: 'dieline',
    gallery: [
      { key: 'mockup', label: 'Mockup', image: img('profoods-makhana/mockup') },
      { key: 'dieline', label: 'Dieline', image: img('profoods-makhana/dieline'), flat: true },
      { key: 'usecase', label: 'Use case', image: img('profoods-makhana/usecase') },
    ],
  },
  {
    slug: 'milletopia',
    name: 'Milletopia',
    meta: '200 G STAND-UP POUCH ✦ MILLETOPIA',
    line: 'Ready-to-eat millet khichdi, noodles, pasta and kheer for fitness-minded eaters.',
    steps: [
      { label: 'BRIEF', text: 'Ready-to-eat, easy-to-make millet foods (jowar, bajra), such as khichdi, noodles, pasta and kheer, for fitness-minded eaters.' },
      { label: 'CONCEPT', text: 'A warm stand-up pouch with the dish in its bowl up front and the name set in English and Hindi, one colour per recipe.' },
      { label: 'ON SHELF', text: 'Khichdi, kheer and noodles line up side by side: each its own colour, all the same wordmark.' },
    ],
    swatches: gen.swatches.milletopia ? [gen.swatches.milletopia[1], gen.swatches.milletopia[2], gen.swatches.milletopia[0]] : ['#CF6759', '#D2AB32', '#F2F2F1'],
    hover: 'dieline',
    gallery: [
      { key: 'mockup', label: 'Mockup', image: img('milletopia/mockup') },
      { key: 'dieline', label: 'Dieline', image: img('milletopia/dieline'), flat: true },
      { key: 'studio', label: 'Studio shot', image: img('milletopia/studio') },
      { key: 'shelf', label: 'Supermarket shelf', image: img('milletopia/shelf') },
    ],
  },
  {
    slug: 'arban-beauty',
    name: 'Arban Beauty',
    meta: 'VITAMIN C SKINCARE CARTON ✦ ARBAN BEAUTY',
    line: 'Organic, nature-led skincare built on natural ingredients and vitamins. This is the Vitamin C range.',
    steps: [
      { label: 'BRIEF', text: 'Organic, nature-led skincare built on natural ingredients and vitamins, including a Vitamin C range.' },
      { label: 'CONCEPT', text: 'A clean white carton, a green leaf emblem and one sliced orange, so the Vitamin C reads at a glance.' },
      { label: 'ON SHELF', text: 'Carton and dropper bottle carry the same orange and the same green, alone on a plinth or lined up in store.' },
    ],
    swatches: gen.swatches['arban-beauty'] ? [gen.swatches['arban-beauty'][1], gen.swatches['arban-beauty'][2], gen.swatches['arban-beauty'][0]] : ['#FB9819', '#B9C8B7', '#F9FAF9'],
    hover: 'lineup',
    gallery: [
      { key: 'mockup', label: 'Carton, flat', image: img('arban-beauty/mockup'), flat: true },
      { key: 'lineup', label: 'Product lineup', image: img('arban-beauty/lineup') },
      { key: 'collection', label: 'Collection display', image: img('arban-beauty/collection') },
      { key: 'shelf', label: 'On the shelf', image: img('arban-beauty/shelf') },
    ],
  },
];

export const allPackProjects: PackProject[] = [honey, ...moreProjects];
