/* ═══════════════════════════════════════════════════
   STREETWEAR CHAPTER — data
   The design list is generated by scripts/prepare-streetwear.ts
   (streetwear.generated.json). Everything else here is hand-editable.
   ═══════════════════════════════════════════════════ */

import generated from './streetwear.generated.json';

export type StreetwearDesign = {
  id: string; // slug, e.g. 'trust-no-bitch-686250'
  order: number; // 1–10 from the model file prefix
  name: string;
  model: string;
  card: string;
  cardAspect: number; // width / height, measured at build
  modelAspect: number; // width / height, measured at build
  art: { front?: string; back?: string; single?: string };
  print: 'FRONT PRINT' | 'BACK PRINT' | 'FRONT + BACK PRINT';
  teeColor?: 'white' | 'black' | 'other'; // sampled
  accent?: string; // sampled hex, falls back to the signal red
  artBg: 'white' | 'black'; // sampled, editable
  sampled?: boolean;
};

/**
 * Per-design overrides on top of the generated values — edit here to rename a design,
 * change a print label, swap the artwork sheet colour or the bloom accent.
 */
const overrides: Record<string, Partial<StreetwearDesign>> = {};

export const streetwear: StreetwearDesign[] = (generated.designs as StreetwearDesign[]).map((d) => ({
  ...d,
  ...overrides[d.id],
}));

export const defaultDesign = 'autism-712945';

/** Showroom split, in fr. Use 65 / 35 for the alternative. */
export const showroomLayout = { stage: 60, rail: 40 };

export const wheel = { driftDegPerSec: 1.2, popScale: 1.3, popRadius: 0.78, selectedNudge: 0.06 };

/** Model-swap transition: a horizontal motion-blur with ghost echoes (see raw-assets/streetwear/effect.jpg). */
export const streetwearEffect = {
  duration: 1.0,
  /** How far the ghost copies spread sideways at the peak, as a fraction of the canvas width */
  spread: 0.16,
  /** Number of ghost copies on each side at the peak */
  ghosts: 3,
  grain: 0.1,
};

export const streetwearIntro = {
  src: '/assets/streetwear/intro.webm',
  poster: '/assets/streetwear/intro-poster.webp',
  available: generated.intro.available,
  duration: generated.intro.duration,
};

export const streetwearCopy = {
  marquee: 'STREETWEAR ✦✦✦ TEE GRAPHICS ✦✦✦',
  kicker: 'Graphics first. The cotton just carries them.',
  hint: 'CLICK THE MODEL ✦ SEE THE ARTWORK',
  wheelCaption: 'HOVER TO OPEN ✦ CLICK TO SELECT ✦ DRAG TO SPIN',
  wheelCaptionTouch: 'TAP TO SELECT ✦ DRAG TO SPIN',
};
